### ISSUE TITLE
Install step3 MySQL errors

### ISSUE THREAD

**Issue by metc** [tony-landis/agilebill#8]
MySQL tables are created, but many errors in the installation step 3:

`5 Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TYPE=MyISAM' at line 11`
...
`ALTER TABLE ab_module ADD INDEX parent (parent_id)
Error (install_sql-3): Table 'agile_bill.ab_module' doesn't exist`

**Comment by ognjenm** [comment]
same here

**Comment by jbenden** [comment]
Try removing lines 194 and 443 from install/install_db_core.inc and try again. This should fix the problem.

**Comment by jbenden** [comment]
Better yet, change the lines to read:

$table_options = array();

**Comment by jbenden** [comment]
I've committed a change that should solve this. Please test so this bug may be closed. Thanks.
